# Generated by Django 2.0.6 on 2018-12-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblRefStatusPenilaian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Keterangan', models.CharField(max_length=50, verbose_name='Keterangan')),
                ('Status', models.IntegerField(default=1, verbose_name='Status')),
            ],
        ),
    ]
