# Generated by Django 2.0.6 on 2018-12-14 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Urusetia', '0002_auto_20181214_1017'),
        ('Pentadbir', '0001_initial'),
        ('Penilaian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeskripsiAttachment', models.CharField(max_length=50, verbose_name='DeskripsiAttachment')),
                ('Path', models.CharField(max_length=50, verbose_name='Path')),
            ],
        ),
        migrations.CreateModel(
            name='AuditTrailJadual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TarikhTransaksi', models.DateField(max_length=60, verbose_name='TarikhTransaksi')),
                ('Tindakan', models.CharField(max_length=50, verbose_name='Tindakan')),
            ],
        ),
        migrations.CreateModel(
            name='Catatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Catatan', models.CharField(max_length=50, verbose_name='Catatan')),
                ('TarikhTransaksi', models.DateField(max_length=60, verbose_name='TarikhTransaksi')),
                ('Tindakan', models.IntegerField(default=1, verbose_name='Tindakan')),
            ],
        ),
        migrations.CreateModel(
            name='Jadual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.IntegerField(default=1, verbose_name='Status')),
                ('AuditeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Urusetia.Auditee')),
                ('CatatanID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Penilaian.Catatan')),
                ('PenggunaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pentadbir.Profil')),
                ('SesiID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Urusetia.Sesi')),
            ],
        ),
        migrations.CreateModel(
            name='Pantau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AuditeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Urusetia.Auditee')),
                ('PenggunaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pentadbir.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Penilaian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Markah', models.FloatField(max_length=50, verbose_name='Markah')),
                ('TarikhPenilaian', models.DateField(max_length=60, verbose_name='TarikhPenilaian')),
                ('Catatan', models.CharField(max_length=50, verbose_name='Catatan')),
                ('AttachmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Penilaian.Attachment')),
                ('JadualID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Penilaian.Jadual')),
                ('PenggunaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pentadbir.Profil')),
                ('SoalanID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Urusetia.Soalan')),
            ],
        ),
        migrations.CreateModel(
            name='RefAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JenisKategori', models.CharField(max_length=50, verbose_name='JenisKategori')),
            ],
        ),
        migrations.CreateModel(
            name='RefStatusPenilaian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusPenilaian', models.CharField(max_length=50, verbose_name='StatusPenilaian')),
                ('Keterangan', models.CharField(max_length=50, verbose_name='Keterangan')),
                ('Status', models.IntegerField(default=1, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='RefTambahan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Keterangan', models.CharField(max_length=50, verbose_name='Catatan')),
            ],
        ),
        migrations.CreateModel(
            name='Tambahan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Catatan', models.CharField(max_length=50, verbose_name='Catatan')),
                ('AttachmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Penilaian.Attachment')),
                ('SesiID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Urusetia.Sesi')),
            ],
        ),
        migrations.DeleteModel(
            name='TblRefStatusPenilaian',
        ),
        migrations.AddField(
            model_name='penilaian',
            name='TambahanID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Penilaian.Tambahan'),
        ),
        migrations.AddField(
            model_name='jadual',
            name='StatusPenilaianID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Penilaian.RefStatusPenilaian'),
        ),
        migrations.AddField(
            model_name='catatan',
            name='JadualID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Penilaian.Jadual'),
        ),
        migrations.AddField(
            model_name='catatan',
            name='PenggunaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pentadbir.Profil'),
        ),
        migrations.AddField(
            model_name='catatan',
            name='SubKomponenID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Urusetia.SubKomponen'),
        ),
        migrations.AddField(
            model_name='audittrailjadual',
            name='JadualID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Penilaian.Jadual'),
        ),
        migrations.AddField(
            model_name='audittrailjadual',
            name='PenggunaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pentadbir.Profil'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='JenisKategoriID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Penilaian.RefAttachment'),
        ),
    ]
