# Generated by Django 2.0.6 on 2018-12-14 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pentadbir', '0001_initial'),
        ('Urusetia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamaAuditee', models.CharField(max_length=100, verbose_name='NamaAuditee')),
                ('Status', models.IntegerField(default=1, verbose_name='StatusAuditee')),
                ('SistemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pentadbir.Sistem')),
            ],
        ),
        migrations.CreateModel(
            name='Jawapan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoJawapan', models.CharField(max_length=10, verbose_name='NoJawapan')),
                ('DeskripsiJawapan', models.CharField(max_length=100, verbose_name='DeskripsiJawapan')),
                ('Nilai', models.IntegerField(default=0, verbose_name='Nilai')),
            ],
        ),
        migrations.CreateModel(
            name='Komponen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KodKomponen', models.CharField(max_length=10, verbose_name='KodKomponen')),
                ('NamaKomponen', models.CharField(max_length=60, verbose_name='NamaKomponen')),
                ('Pemberat', models.IntegerField(default=0, verbose_name='Pemberat')),
            ],
        ),
        migrations.CreateModel(
            name='RefSkala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamaSkala', models.CharField(max_length=50, verbose_name='NamaSkala')),
                ('Deskripsi', models.CharField(max_length=50, verbose_name='Deskripsi')),
                ('NilaiSkala', models.IntegerField(default=1, verbose_name='NilaiSkala')),
                ('Status', models.IntegerField(default=1, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Sesi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Siri', models.CharField(max_length=50, verbose_name='Siri')),
                ('TarikhMula', models.DateTimeField(auto_now_add=True, null=True, verbose_name='TarikhMula')),
                ('TarikhTamat', models.DateTimeField(auto_now_add=True, null=True, verbose_name='TarikhTamat')),
                ('TarikhMulaAudit', models.DateTimeField(auto_now_add=True, null=True, verbose_name='TarikhMulaAudit')),
                ('TarikhTamatAudit', models.DateTimeField(auto_now_add=True, null=True, verbose_name='TarikhTamatAudit')),
                ('Status', models.IntegerField(default=1, verbose_name='StatusSesi')),
                ('SistemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pentadbir.Sistem')),
            ],
        ),
        migrations.CreateModel(
            name='Soalan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoSoalan', models.CharField(max_length=10, verbose_name='NoSoalan')),
                ('DeskripsiSoalan', models.CharField(max_length=100, verbose_name='DeskripsiSoalan')),
                ('Status', models.IntegerField(default=1, verbose_name='Statussoalan')),
                ('KomponenID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Urusetia.Komponen')),
            ],
        ),
        migrations.CreateModel(
            name='SubAuditee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamaSubAuditee', models.CharField(max_length=100, verbose_name='NamaSubAuditee')),
                ('Status', models.IntegerField(default=1, verbose_name='StatusSubAuditee')),
                ('AuditeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Urusetia.Auditee')),
            ],
        ),
        migrations.CreateModel(
            name='SubKomponen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubKodKomponen', models.CharField(max_length=10, verbose_name='SubKodKomponen')),
                ('NamaSubKomponen', models.CharField(max_length=100, verbose_name='NamaSubKomponen')),
                ('Pemberat', models.IntegerField(default=0, verbose_name='Pemberat')),
                ('KomponenID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Urusetia.Komponen')),
                ('RefSkalaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Urusetia.RefSkala')),
            ],
        ),
        migrations.DeleteModel(
            name='TblSesi',
        ),
        migrations.AddField(
            model_name='komponen',
            name='SesiID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Urusetia.Sesi'),
        ),
        migrations.AddField(
            model_name='jawapan',
            name='SoalanID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Urusetia.Soalan'),
        ),
    ]
