# Generated by Django 2.0.6 on 2018-12-14 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peranan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nokpten', models.CharField(max_length=12, unique=True)),
                ('Status', models.IntegerField(default=1, verbose_name='Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RefPeranan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Peranan', models.CharField(max_length=100, verbose_name='Peranan')),
                ('KodPeranan', models.IntegerField(default=1, verbose_name='KodPeranan')),
                ('Keterangan', models.CharField(max_length=200, verbose_name='Keterangan')),
            ],
        ),
        migrations.CreateModel(
            name='Sistem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamaSistem', models.CharField(max_length=200, verbose_name='NamaSistem')),
                ('Tahun', models.IntegerField(verbose_name='Tahun')),
                ('Status', models.IntegerField(default=1, verbose_name='Status')),
                ('PemilikSistem', models.CharField(max_length=200, verbose_name='PemilikSistem')),
            ],
        ),
        migrations.AddField(
            model_name='peranan',
            name='Peranan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pentadbir.RefPeranan'),
        ),
        migrations.AddField(
            model_name='peranan',
            name='Sistem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pentadbir.Sistem'),
        ),
        migrations.AddField(
            model_name='peranan',
            name='UProfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pentadbir.Profil'),
        ),
    ]
