# Generated by Django 2.1.2 on 2018-12-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pentadbir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peranan',
            name='nokpten',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
